filepath: examples/bvh/mixamo/gangnamstyle.bvh
start_frame_idx: 0
end_frame_idx: 250
groundplane_joint: mixamorig:RightToeBase
forward_perp_joint_vectors:
  - - mixamorig:LeftShoulder
    - mixamorig:RightShoulder
  - - mixamorig:LeftUpLeg
    - mixamorig:RightUpLeg
scale: 0.01
up: +y
